android: use llvm-strip for lld to fix broken arm64 libswscale.so. #41
java.lang.UnsatisfiedLinkError: dlopen failed: invalid ELF file "/data/app/io.fd.viper-ona0NuZvuqURUW725tsRew==/lib/arm64/libswscale.so" load segment[4]: p_offset (0x41000) + p_filesz (0x0) ( = 0x41000) past end of file (0x40a60)
other modules and libffmpeg.so are fine.
broken since ndk r21. seems fixed in upstream gnu ld.